modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="fudgerunes"
version="${file.jarVersion}"
displayName="Fudge's R.U.N.E.S."
logoFile="examplemod.png" #optional
authors="Fudge's R.U.N.E.S. by IAmTheFudge (aka Fudge)" #optional
description='''
Welcome to Fudge's Really Useful New Enhancement System!
'''

[[dependencies.fudgerunes]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.fudgerunes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
